webappfiles/auth.py
from webappfiles import dbconnect

import mysql.connector
from werkzeug.security import generate_password_hash, check_password_hash
from flask import Blueprint, render_template, request, flash,  redirect, session, url_for
from . import mail

from flask_mail import Mail, Message
mail = Mail()


auth = Blueprint('auth', __name__)


@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        email = request.form['txtemail']
        first_name = request.form['txtfn']
        last_name = request.form['txtln']
        password1 = request.form['txtpwd']
        password2 = request.form['txtcpwd']

        cur, con = dbconnect.get_connection()
        sql = "select email from tbluser where email= %s"
        val = (email,)
        cur.execute(sql, val)
        rows = cur.fetchall()
        count = cur.rowcount

        if (count > 0):
            flash('User already exists.', category='error')
        elif (len(email) < 5):
            flash('Email must be greater than 4 characters.', category='error')
        elif (len(first_name) < 3):
            flash('First name must be greater than 2 characters.', category='error')
        elif (password1 != password2):
            flash('Passwords don\'t match.', category='error')
        elif (len(password1) < 3):
            flash('Password must be at least 3 characters.', category='error')
        else:
            passw = generate_password_hash(password1, method='sha256')
            sql2 = "INSERT into tbluser (email, firstname, lastname, password) values (%s,%s,%s,%s)"
            val2 = (email, first_name, last_name, passw)
            cur.execute(sql2, val2)
            con.commit()
            msg = str(cur.rowcount) + " record added, "
            msg1 = Message('BoMarseBoutik store',
                           sender='jinsama16@gmail.com', recipients=[email])
            msg1.body = "Welcome to bomarseboutik store " + first_name + "\r\n"
            msg1.body += "You are now a member and may access the website \r\n "
            msg1.body += "@ http://localhost:5000/"
            mail.send(msg1)
            flash(msg + ' account created!', category='success')
        return redirect(url_for('auth.login'))
    return render_template("signup.html")


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['txtemail']
        pwd = request.form['txtpwd']
        cur, con = dbconnect.get_connection()
        sql = "select password, email, user_id, firstname from tbluser where email= %s"
        val = (email,)
        cur.execute(sql, val)
        rows = cur.fetchall()
        count = cur.rowcount

        for row in rows:
            passw = row[0]

        if (count > 0):
            if check_password_hash(passw, pwd):
                session['userid'] = rows[0][2]
                session['fn'] = rows[0][3]
                flash('Logged in successfully!', category='success')
                return redirect(url_for('views.profile'))
            else:
                flash('Incorrect password, pls try again.', category='error')
        else:
            flash('Email does not exist.', category='error')
    return render_template("login.html")


@auth.route('/logout/')
def logout():
    session.pop('userid')
    return redirect('/')

webappfiles/views.py
from flask import Blueprint, render_template, request, session, redirect, flash


import mysql.connector
from webappfiles import dbconnect

from datetime import datetime
import os

views = Blueprint('views', __name__)
# referring to the default page via the “/” route

cur, con = dbconnect.get_connection()


@views.route("/")
def home():
 

    return render_template("index.html")


@views.route("/about/")
def about():
    return render_template("about.html")


@views.route("/adminhome/")
def adminhome():
    return render_template("adminhome.html")


@views.route("/help/")
def help():
    return render_template("help.html")


@views.route("/addbook/")
def add_book():
    cur.execute("select * from tblgenre")
    rows1 = cur.fetchall()

    cur.execute("select * from tbllanguage")
    rows2 = cur.fetchall()

    cur.execute("select * from tblauthor")
    rows3 = cur.fetchall()
    return render_template("addbook.html", rows1=rows1, rows2=rows2, rows3=rows3)


@views.route("/savedetails", methods=["POST"])
def saveDetails():
    msg = "msg"
    if request.method == "POST":
        try:
            # add codes to retrieve the form values
            title = request.form["txttitle"]
            isbn = request.form["txtisbn"]
            price = request.form["txtprice"]
            qty = request.form["txtqty"]
            numpages = request.form["txtnumpage"]
            genre = request.form["ddlgenre"]
            lang = request.form["ddllang"]
            instk = bool(request.form.get("chkavailable"))
            f = request.files["filecover"]
            f.save(os.path.join("./webappfiles/static/images", f.filename))
            full_filename = os.path.join("/static/images", f.filename)
            dt = request.form["txtpdate"]

            sql = """INSERT into tblbook(title, isbn, price, quantity, total_pages, publication_date, genre_id, language_id, book_cover, instock)
            values (% s, % s, % s, % s, % s, % s, % s, % s, % s, % s)"""
            # add the form variables for each column
            val = (title, isbn, price, qty, numpages,
                   dt, genre, lang, full_filename, instk)
            cur.execute(sql, val)
            con.commit()
            msg = str(cur.rowcount) + " book added"

            authids = request.form.getlist("ddlauthor")
            lastbkid = cur.lastrowid
            for aid in authids:
                sql2 = "INSERT INTO tblbook_author (book_id, author_id)VALUES (%s, %s)"
                val2 = (lastbkid, aid)
                cur.execute(sql2, val2)
                con.commit()

        except Exception as e:
            con.rollback()
            msg = "Book cannot be added " + str(e)
        finally:
            # pass the msg variable to the return statement
            return render_template("addbook.html", msg=msg, title=title)
            con.close()


@views.route("/viewbook/")
def view_book():
    cur.execute("SELECT * FROM tblbook bk INNER JOIN tblbook_author bka on \
    (bk.book_id=bka.book_id) \
    INNER JOIN tblauthor auth on (auth.author_id=bka.author_id)")
    rows = cur.fetchall()
    return render_template("viewbooks.html", rows=rows)


@views.route("/searchbook/")
def search_book():
    return render_template("search.html")


@views.route("/searchbk/", methods=["GET"])
def searchbook():
    # retrieve the querystring txtlang from the URL
    lang = request.args.get("txtlang")
    try:
        sql = "select * from tblbook bk INNER JOIN tbllanguage lg ON \
        bk.language_id=lg.language_id WHERE language_name LIKE %s ORDER BY title DESC"
        val = ('%' + lang + '%',)
        cur.execute(sql, val)
        rows = cur.fetchall()
        msg = str(cur.rowcount) + " record found!"
    except:
        msg = "There was an issue while searching!"
    finally:
        return render_template("search.html", msg=msg, rows=rows, lang=lang)


@views.route("/updatebook/")
def update_book():
    return render_template("updatebook.html")


@views.route("/updaterecord/", methods=["POST"])
def updaterecord():
    # retrieve the form values
    price = request.form["txtprice"]
    isbn = request.form["txtisbn"]
    try:
        sql = "UPDATE tblbook SET price = %s where isbn = %s"
        val = (price, isbn)
        cur.execute(sql, val)
        con.commit()
        msg = str(cur.rowcount) + " record successfully updated"
    except:
        msg = "Cannot be updated"
    finally:
        return render_template("updatebook.html", msg=msg)


@views.route("/deletebook/")
def delete_book():
    return render_template("deletebook.html")


@views.route("/deleterecord/")
def deleterecord():
    # retrieve the form value
    isbn = request.form["txtisbn"]
    try:
        sql = "DELETE FROM tblbook WHERE isbn = %s"
        val = (isbn,)
        cur.execute(sql, val)
        con.commit()
        msg = str(cur.rowcount) + " record successfully deleted"
    except:
        msg = "Cannot be deleted"
    finally:
        return render_template("deletebook.html", msg=msg)


@views.route("/searchcustomer/")
def search_customer():
    return render_template("searchcustomer.html")


@views.route("/manageauthor/")
def manage_author():
    return render_template("manageauthor.html")


@views.route("/profile/")
def profile():
    if 'userid' in session:
        cur, con = dbconnect.get_connection()
        sql = "SELECT * FROM tbluser where user_id = %s"
        val = (session.get('userid'),)
        cur.execute(sql, val)
        rows = cur.fetchall()
        return render_template('profile.html', rows=rows)
    else:
        return redirect('/')


@views.route("/updateprofile/", methods=["GET", "POST"])
def update_profile():
    if request.method == "POST":
        email = request.form['txtemail']
        first_name = request.form['txtfn']
        last_name = request.form['txtln']
        phone = request.form['txtphone']
        try:
            cur, con = dbconnect.get_connection()
            sql = "UPDATE tbluser SET email = %s, firstname = %s, lastname = %s , phone = %s where user_id = %s"
            val = (email, first_name, last_name, phone, session['userid'])
            cur.execute(sql, val)
            con.commit()
            msg = str(cur.rowcount) + " record successfully updated"
            flash(msg, category='success')
        except:
            msg = "Cannot be updated"
            flash(msg, category='error')
        finally:
            return redirect('/profile/')
    else:
        return redirect('/login/')


@views.route("/booklisting/")
def book_listing():
    cur, con = dbconnect.get_connection()
    cur.execute("SELECT * FROM tblbook")
    rows = cur.fetchall()
    return render_template('booklisting.html', rows=rows)

webappfiles/templates/about.html
<!DOCTYPE html>
<html lang="en">
 <head>
 <meta charset="utf-8">
 <title>About Us</title>
 </head>
 <body>

    {% extends "basecust.html" %}

    {% block content %}

    <div class="row">
        <div class="col-md-12 pt-5">

 <h1> About BoMarse Boutik </h1>
 <p> Established in the year 1979 and located in Vacoas.</p>
 <p> This small company focusses mainly on the sale of second hand books.</p>

</div>
</div>

{% endblock %}

</body>
</html>

webappfiles/templates/addbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    {% extends "baseadmin.html" %}
    {% block content %}

    {{ msg }} {{title}}

    <form class="row" action="/savedetails" method="post"
    enctype="multipart/form-data">
    <h2 class="mt-3">Add Book</h2>
    <div class="col-md-6 pt-5">
    <div class="mb-3">
    <label for="txttitle" class="form-label">Title</label>
    <input type="text" class="form-control" name="txttitle"
    id="txttitle">
    </div>
    <div class="mb-3">
    <label for="txtisbn" class="form-label">ISBN</label>
    <input type="text" class="form-control" id="txtisbn" name="txtisbn">
    </div>
    <div class="mb-3">
    <label for="txtprice" class="form-label">Price</label>
    <input type="text" class="form-control" id="txtprice"
    name="txtprice">
    </div>
    <div class="mb-3">
    <label for="txtqty" class="form-label">Quantity</label>
    <input type="text" class="form-control" id="txtqty" name="txtqty">
    </div>
    <div class="mb-3">
    <label for="txtnumpage" class="form-label">Number of pages</label>
    <input type="text" class="form-control" id="txtnumpage"
    name="txtnumpage">
    </div>
    </div>

    <div class="col-md-6 pt-5">
    <div class="mb-3">
    <label for="txtpdate" class="form-label">Publication Date</label>
    <input autocomplete="off" class="form-control" id="txtpdate"
    name="txtpdate">
    </div>
    <div class="mb-3">
    <select id="ddlgenre" name="ddlgenre"
    class="form-select form-select-md mb-3"
    aria-label=".form-select-lg example">
    <option>Select Genre</option>
    {% for g in rows1 %}
    <option value="{{g[0]}}">
        {{g[1]}}
    </option>
    {% endfor %}
    </select>
    </div>
    <div class="mb-3">
    <select id="ddlauthor" multiple name="ddlauthor"
    class="form-select form-select-md mb-3"
    aria-label=".form-select-lg example">
    <option>Select Author</option>
    {% for a in rows3 %}
    <option value="{{a[0]}}">
        {{a[1]}} {{a[2]}}
    </option>
    {% endfor %}
    </select>
    </div>
    <div class="mb-3">
    <select id="ddllang" name="ddllang"
    class="form-select form-select-md mb-3"
    aria-label=".form-select-lg example">
    <option>Select Language</option>
    {% for l in rows2 %}
    <option value="{{l[0]}}">
        {{l[2]}}
    </option>
    {% endfor %}
    </select>
    </div>
    <div class="mb-3">
    <label for="filecover" class="form-label">Upload Book Cover</label>
    <input class="form-control form-control-lg" id="filecover"
    name="filecover" type="file">
    </div>
    <div class="form-check mb-3">
    <input class="form-check-input" type="checkbox" value="1"
    id="chkavailable" name="chkavailable">
    <label class="form-check-label" for="chkavailable">
    In Stock
    </label>
    </div>
    </div>
    <button type="submit" class="col-6 btn btn-primary mx-auto">Add 
    Book</button>
    </form>
    

    {% endblock %}

</body>
</html>

webappfiles/templates/baseadmin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.min.css') }}">
    
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
    
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    
    <link rel="stylesheet" href="{{ url_for('static', filename='css/baseadmin.css') }}">

    <link type="text/css"href="https://code.jquery.com/ui/1.12.1/themes/hot-sneaks/jquery-ui.css"rel="stylesheet" />
    
    <script src="https://kit.fontawesome.com/0c54b7787d.js"></script>

</head>
<body>

<header class="row">

    <nav class="navbar fixed-top navbar-expand-lg bg-danger bg-gradient 
navbar-dark">
<div class="container-fluid">
<a class="navbar-brand" href="#">BoMarse Boutik</a>
<button class="navbar-toggler" type="button"
data-bs-toggle="collapse" data-bs-target="#navbarScroll"
aria-controls="navbarScroll" aria-expanded="false"
aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarScroll">
<ul class="navbar-nav me-auto my-2 my-lg-0"
style="--bs-scroll-height: 100px;">
<li class="nav-item">
<a class="nav-link active" aria-current="page" href="{{ url_for('views.adminhome') }}">Home</a>
</li>
<li class="nav-item">
<a class="nav-link" href="#" disabled>Link</a>
</li>
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown"
role="button" data-bs-toggle="dropdown"
aria-expanded="false">
Manage Author
</a>
<ul class="dropdown-menu"
aria-labelledby="navbarScrollingDropdown">
<li><a class="dropdown-item" href="{{ url_for('views.manage_author') }}">View Author</a></li>
<li><a class="dropdown-item" href="#">Another action</a></li>
<li><hr class="dropdown-divider"></li>
<li><a class="dropdown-item" href="#">Something else here</a></li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link" href="{{ url_for('views.help') }}" tabindex="-1"
aria-disabled="true">Help Corner</a>
</li>
</ul>
<form class="d-flex">
<input class="form-control me-2" type="search" placeholder="Search" arialabel="Search">
<button class="btn btn-outline-warning" type="submit">Search</button>
</form>
</div>

</div>
</nav>


</header>


<div class="container-fluid mt-5">
<div class="row">
<nav class="col-md-2 mt-2 bg-dark flex-column min-vh-100">
<div class="accordion mt-4" id="accordionExample">
<div class="accordion-item">
<h2 class="accordion-header" id="headingdashboard">
<a class="nav-link" href="#"><strong>Dashboard</strong></a>
</h2>
</div>
<div class="accordion-item">
<h2 class="accordion-header" id="headingOne">
<button class="accordion-button collapsed" type="button"
data-bs-toggle="collapse"
data-bs-target="#collapseOne" aria-expanded="false"
aria-controls="collapseOne">
Manage Book
</button>
</h2>
<div id="collapseOne" class="accordion-collapse collapse"
aria-labelledby="headingOne"
data-bs-parent="#accordionExample">
<div class="accordion-body">
<a class="nav-link" href="{{ url_for('views.add_book') }}"><strong>Add Book</strong></a>
<a class="nav-link" href="{{ url_for('views.view_book') }}"><strong>Book Listing</strong></a>
<a class="nav-link" href="{{ url_for('views.search_book') }}"><strong>Search Book</strong></a>
<a class="nav-link" href="{{ url_for('views.update_book') }}"><strong>Update Book</strong></a>
<a class="nav-link" href="{{ url_for('views.delete_book') }}"><strong>Delete Book</strong></a>
</div>
</div>
</div>
<div class="accordion-item">
<h2 class="accordion-header" id="headingTwo">
<button class="accordion-button collapsed" type="button"
data-bs-toggle="collapse"
data-bs-target="#collapseTwo" aria-expanded="false"
aria-controls="collapseTwo">
Manage Customer
</button>

</h2>
<div id="collapseTwo" class="accordion-collapse collapse"
aria-labelledby="headingTwo"
data-bs-parent="#accordionExample">
<div class="accordion-body">
<a class="nav-link" href="{{ url_for('views.search_customer') }}"><strong>Search Customer</strong></a>
<a class="nav-link" href="#"><strong>Link 3</strong></a>
</div>
</div>
</div>
<div class="accordion-item">
<h2 class="accordion-header" id="headingThree">
<button class="accordion-button collapsed" type="button"
data-bs-toggle="collapse"
data-bs-target="#collapseThree" aria-expanded="false"
aria-controls="collapseThree">
Accordion Item #3
</button>
</h2>
<div id="collapseThree" class="accordion-collapse collapse" arialabelledby="headingThree"
data-bs-parent="#accordionExample">
<div class="accordion-body">
<a class="nav-link" href="#"><strong>Link 3</strong></a>
<a class="nav-link" href="#"><strong>Link 3</strong></a>
</div>
</div>
</div>
</div>
</nav>

<main class="col-md-7 offset-md-1 py-5">
    {% block content %}
    {% endblock %}
</main>

</div>
</div>



<script type="text/javascript" src="{{url_for('static', filename='js/jquery-3.6.0.js') }}"></script>

<script src="{{url_for('static', filename='js/app.js')}}"></script>

<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>

<script type="text/javascript"src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>

<script type="text/javascript" src="{{url_for('static', filename='js/bootstrap.min.js') }}"></script>

<script src="{{url_for('static', filename='js/image-popup.js')}}"></script>


<script type="text/javascript">
    $(function () {
    $("#txtpdate").datepicker({ 
    dateFormat: 'yy/mm/dd'
    });
    });
</script>

</body>
</html>

webappfiles/templates/basecust.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.min.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
    <script src="https://kit.fontawesome.com/0c54b7787d.js"></script>
</head>
<body>

    <header class="row">

        <nav class="navbar fixed-top navbar-expand-lg bg-danger bg-gradient navbar-dark">
<div class="container-fluid">
<a class="navbar-brand" href="#">BoMarse Boutik</a>
<button class="navbar-toggler" type="button"
data-bs-toggle="collapse" data-bs-target="#navbarScroll"
aria-controls="navbarScroll" aria-expanded="false"
aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarScroll">
<ul class="navbar-nav me-auto my-2 my-lg-0"
style="--bs-scroll-height: 100px;">
<li class="nav-item">
<a class="nav-link active" aria-current="page" href="{{ url_for('views.book_listing') }}">viewbook</a>
</li>
<li class="nav-item">
<a class="nav-link" href="#" disabled>Link</a>
</li>
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown"
role="button" data-bs-toggle="dropdown"
aria-expanded="false">Link</a>
<ul class="dropdown-menu"
aria-labelledby="navbarScrollingDropdown">
<li><a class="dropdown-item" href="#">Action</a></li>
<li><a class="dropdown-item" href="#">Another action</a></li>
<li><hr class="dropdown-divider"></li>
<li><a class="dropdown-item" href="#">Something else here</a></li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link" href="{{ url_for('views.about') }}" tabindex="-1"aria-disabled="true">About Us</a>
</li>
</ul>
<form class="d-flex">
<input class="form-control me-2" type="search" placeholder="Search"
aria-label="Search">
<button class="btn btn-outline-warning" type="submit">Search</button>

{% if 'userid' not in session %}

<a class="btn btn-secondary mx-1 my-1" href="{{ url_for('auth.signup') }}">Join</a>

<a class="btn btn-warning mx-1" href="{{ url_for('auth.login') }}">Log In</a>

{% else %}
<a class="btn btn-outline-warning text-white mx-1"
href="{{ url_for('auth.logout') }}">Logout</a>

<a class="btn btn-warning mx-1" href="{{ url_for('views.profile') }}">{{session["fn"]}}</a>

{% endif %}
</form>
</div>
</div>
</nav>

    </header>

    <main class="container py-5">

        {% block content %}
        
        {% with messages = get_flashed_messages(with_categories=true) %} 
                {% if messages %} 
                        {% for category, message in messages %} 
                                {% if category == '' %}
                                        <div class="alert alert-danger alert-dismissible fade show"
                                        role="alert">
                                        {{ message }}
                                        <button type="button" class="btn-close" data-bs-dismiss="alert">
                                        </button>
                                        </div>
                                {% else %}
                                        <div class="alert alert-success alert-dismissible fade show"
                                        role="alert">
                                        {{ message }}
                                        <button type="button" class="btn-close" data-bs-dismiss="alert">
                                        </button>
                                        </div>
                                {% endif %} 
                        {% endfor %} 
                {% endif %} 
        {% endwith %}

        {% endblock %}
    </main>

    <footer class="bg-dark text-center text-white">
        <!-- Grid container -->
        <div class="container p-4">
        <!-- Section: Social media -->
        <section class="m-5">
        <!-- Facebook -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
        class="fab fa-facebook-f"></i></a>
        <!-- Twitter -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
        class="fab fa-twitter"></i></a>
        <!-- Linkedin -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
        class="fab fa-linkedin-in"></i></a>
        </section>
        <!-- Section: Social media -->
        </div>
        <!-- Grid container -->
        <!-- Copyright -->

        <div class="p-5" style="background-color: rgba(0, 0, 0, 0.2);">
            <h4>&copy;2022 bomarse : : boutik <span class="float-end">Like us: 
            www.facebook.com/bomarseboutik/</span></h4>
            </div>
            <!-- Copyright -->
            </footer>

    <script type="text/javascript" src="{{url_for('static', filename='js/jquery-3.6.0.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/bootstrap.min.js') }}"></script>

</body>
</html>

webappfiles/templates/booklisting.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
</head>
<body>

    {% extends "basecust.html" %}
    {% block content %}
    
    
    <h1 class="text-center text-info mt-4">** Book Listing **</h1>
    <hr>
    <div class="row text-center">
    {% for row in rows %}
    <div class="col-md-4 pt-5">
    <div class="card mx-auto border border-2 border-info p-2"
    style="width: 18rem;">
    <img src="{{row.8}}" class="card-img-top">
    <div class="card-body">
    <h5 class="card-title text-success">{{row.1}}</h5>
    <p class="card-text"><b>Price:</b> Rs.{{row.5}}</p>
    <a href="#" class="btn btn-primary">Reserve Book</a>
    </div>
    </div>
    </div>
    {% endfor %}
    </div>

    {% endblock %}
</body>
</html>

webappfiles/templates/help.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    {% extends "baseadmin.html" %}
    {% block content %}

    <div class="row">
        <div class="col-md-12 pt-5">
         <h1> Help corner</h1>
         <p>Under construction!</p>
         </div>
    </div>

    {% endblock %}
</body>
</html>

webappfiles/templates/index.html
<!DOCTYPE html>
<html lang="en">
 <head>
 <meta charset="utf-8">
 <title></title>
 <style>
    span.emoj {
        font-size: 60px;
    }
 </style>
 </head>
 <body>

    {% extends "basecust.html" %}

    {% block content %}

    <div class="row text-center">
        <div class="col-md-6 pt-5 mx-auto">

<h2>“Old books exert a strange fascination for me -- their smell, their feel, their history;
wondering who might have owned them, how they lived, what they felt.”
― Lauren Willig</h2>

        <div class="d-grid gap-1 col-6 mx-auto mt-5">
            <span class="emoj"> {{x}} </span>
        </div>
        </div>
    </div>

    {% endblock %}

</body>
</html>

webappfiles/templates/searchcustomer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    {% extends "baseadmin.html" %}
    {% block content %}

    <form action="/searchcustomer" method="get" class="mt-5">
        <h3>Search Customer</h3>
        <div class="row">
        <div class="col-md-5 mb-5">
        <label for="txtcust" class="form-label">Enter Customer 
        name:</label>
        <input type="text" class="form-control" name="txtcust" 
        id="txtcust" />
        </div>
        </div>
        <div class="row">
        <div class="col-md-5 mb-5">
        <input
        type="submit"
        class="btn btn-outline-primary"
        value="Search Customer"/>
        </div>
        </div>
    </form>
    

    {% endblock %}

</body>
</html>